# Generated migration to add Machine model using RunSQL
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Create machine table with all fields
            sql="""
                CREATE TABLE "machine" (
                    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    "timestamp" datetime NOT NULL,
                    "machine_original_id" integer NULL REFERENCES "machine" ("id") ON DELETE SET NULL,
                    "machine_owner_user_id" bigint NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
                    "machine_owner_team_id" integer NULL REFERENCES "Team" ("id") ON DELETE SET NULL,
                    "machine_name" varchar(500) NOT NULL,
                    "machine_description" text NOT NULL,
                    "machine_level" integer NOT NULL,
                    "machine_data_source_is_public" bool NOT NULL,
                    "machine_data_source_sample_only_public" bool NOT NULL,
                    "machine_data_source_price_usd" decimal(32, 10) NULL,
                    "machine_api_solving_is_public" bool NOT NULL,
                    "machine_api_solving_price_usd" decimal(32, 10) NULL,
                    "machine_machine_is_duplicatable" bool NOT NULL,
                    "machine_machine_copy_cost_usd" decimal(32, 10) NULL,
                    "machine_machine_copy_update_cost_usd" decimal(32, 10) NULL,
                    "machine_billing_cost_solving_usd" decimal(32, 10) NULL,
                    "machine_billing_cost_training_usd" decimal(32, 10) NULL,
                    "machine_columns_errors" text NOT NULL,
                    "machine_columns_warnings" text NOT NULL,
                    "dfr_columns_description_user_df" text NOT NULL,
                    "dfr_columns_type_user_df" text NOT NULL,
                    "dfr_columns_python_user_df" text NOT NULL,
                    "mdc_columns_name_input_user_df" text NULL,
                    "mdc_columns_name_output_user_df" text NULL,
                    "mdc_columns_name_input" text NOT NULL,
                    "mdc_columns_name_output" text NOT NULL,
                    "mdc_columns_total_count" integer NULL,
                    "mdc_columns_input_count" integer NULL,
                    "mdc_columns_output_count" integer NULL,
                    "mdc_columns_data_type" text NOT NULL,
                    "mdc_columns_count_of_datatypes" text NOT NULL,
                    "mdc_columns_input_count_of_datatypes" text NOT NULL,
                    "mdc_columns_output_count_of_datatypes" text NOT NULL,
                    "mdc_columns_json_structure" text NOT NULL,
                    "mdc_columns_unique_values_count" text NOT NULL,
                    "mdc_columns_missing_percentage" text NOT NULL,
                    "mdc_columns_most_frequent_values_count" text NOT NULL,
                    "mdc_columns_values_mean" text NOT NULL,
                    "mdc_columns_values_std_dev" text NOT NULL,
                    "mdc_columns_values_skewness" text NOT NULL,
                    "mdc_columns_values_kurtosis" text NOT NULL,
                    "mdc_columns_values_min" text NOT NULL,
                    "mdc_columns_values_max" text NOT NULL,
                    "mdc_columns_values_quantile02" text NOT NULL,
                    "mdc_columns_values_quantile03" text NOT NULL,
                    "mdc_columns_values_quantile07" text NOT NULL,
                    "mdc_columns_values_quantile08" text NOT NULL,
                    "mdc_columns_values_sem" text NOT NULL,
                    "mdc_columns_values_median" text NOT NULL,
                    "mdc_columns_values_mode" text NOT NULL,
                    "mdc_columns_values_str_percent_uppercase" text NOT NULL,
                    "mdc_columns_values_str_percent_lowercase" text NOT NULL,
                    "mdc_columns_values_str_percent_digit" text NOT NULL,
                    "mdc_columns_values_str_percent_punctuation" text NOT NULL,
                    "mdc_columns_values_str_percent_operators" text NOT NULL,
                    "mdc_columns_values_str_percent_underscore" text NOT NULL,
                    "mdc_columns_values_str_percent_space" text NOT NULL,
                    "mdc_columns_values_str_language_en" text NOT NULL,
                    "mdc_columns_values_str_language_fr" text NOT NULL,
                    "mdc_columns_values_str_language_de" text NOT NULL,
                    "mdc_columns_values_str_language_it" text NOT NULL,
                    "mdc_columns_values_str_language_es" text NOT NULL,
                    "mdc_columns_values_str_language_pt" text NOT NULL,
                    "mdc_columns_values_str_language_others" text NOT NULL,
                    "mdc_columns_values_str_language_none" text NOT NULL,
                    "machine_is_data_lines_training_count_limit_enabled" bool NOT NULL,
                    "machine_data_lines_training_count_limit" integer NULL,
                    "machine_is_re_run_mdc" bool NOT NULL,
                    "machine_is_re_run_ici" bool NOT NULL,
                    "machine_is_re_run_fe" bool NOT NULL,
                    "machine_is_re_run_enc_dec" bool NOT NULL,
                    "machine_is_re_run_nn_config" bool NOT NULL,
                    "machine_is_re_run_model" bool NOT NULL,
                    "fe_budget_total" decimal(32, 10) NULL,
                    "fe_columns_fet" text NULL,
                    "fe_count_of_fet" text NULL,
                    "fe_find_delay_sec" integer NULL,
                    "fe_columns_inputs_importance_evaluation" text NULL,
                    "fe_columns_inputs_importance_find_delay_sec" integer NULL,
                    "enc_dec_configuration_id" integer NULL UNIQUE REFERENCES "encdec_configuration" ("id") ON DELETE SET NULL,
                    "enc_dec_columns_info_input_encode_count" integer NULL,
                    "enc_dec_columns_info_output_encode_count" integer NULL,
                    "parameter_nn_loss" varchar(100) NULL,
                    "parameter_nn_loss_scaler" decimal(32, 10) NULL,
                    "parameter_nn_optimizer" varchar(150) NULL,
                    "parameter_nn_shape" text NULL,
                    "parameter_nn_find_delay_sec" integer NULL,
                    "training_nn_model_id" integer NULL UNIQUE REFERENCES "nn_model" ("id") ON DELETE SET NULL,
                    "training_training_total_delay_sec" decimal(32, 10) NULL,
                    "training_training_cell_delay_sec" decimal(32, 10) NULL,
                    "training_date_time_machine_model" datetime NULL,
                    "training_training_epoch_count" integer NULL,
                    "training_training_batch_size" integer NULL,
                    "training_total_training_line_count" integer NULL,
                    "training_type_machine_hardware" text NULL,
                    "log_work_message" text NULL,
                    "log_work_status" text NULL,
                    "training_eval_loss_sample_training" decimal(32, 10) NULL,
                    "training_eval_loss_sample_evaluation" decimal(32, 10) NULL,
                    "training_eval_loss_sample_training_noise" decimal(32, 10) NULL,
                    "training_eval_loss_sample_evaluation_noise" decimal(32, 10) NULL,
                    "training_eval_accuracy_sample_training" decimal(32, 10) NULL,
                    "training_eval_accuracy_sample_evaluation" decimal(32, 10) NULL,
                    "training_eval_accuracy_sample_training_noise" decimal(32, 10) NULL,
                    "training_eval_accuracy_sample_evaluation_noise" decimal(32, 10) NULL,
                    "training_eval_outputs_cols_loss_sample_evaluation" text NULL,
                    "training_eval_outputs_cols_accuracy_sample_evaluation" text NULL
                );
                
                CREATE INDEX "machine_timestamp_idx" ON "machine" ("timestamp" DESC);
                CREATE INDEX "machine_owner_user_idx" ON "machine" ("machine_owner_user_id");
                CREATE INDEX "machine_owner_team_idx" ON "machine" ("machine_owner_team_id");
            """,
            reverse_sql='DROP TABLE "machine";'
        ),
    ]
